-- MySQL 8 schema. The running prototype uses SQLAlchemy and can default to SQLite.
CREATE DATABASE IF NOT EXISTS smart_study CHARACTER SET utf8mb4; USE smart_study;
CREATE TABLE departments (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE);
CREATE TABLE subjects (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, department_id INT NOT NULL, academic_year VARCHAR(30), semester VARCHAR(30), FOREIGN KEY(department_id) REFERENCES departments(id));
CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(120) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, role ENUM('student','faculty','admin') NOT NULL DEFAULT 'student', department_id INT, academic_year VARCHAR(30), created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(department_id) REFERENCES departments(id));
CREATE TABLE resources (id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(200) NOT NULL,description TEXT,resource_type VARCHAR(50) NOT NULL,file_path VARCHAR(255),department_id INT NOT NULL,academic_year VARCHAR(30),semester VARCHAR(30),subject_id INT,unit VARCHAR(40),topic VARCHAR(150),tags VARCHAR(500),exam_type VARCHAR(80),uploader_id INT NOT NULL,upload_date DATETIME DEFAULT CURRENT_TIMESTAMP,view_count INT DEFAULT 0,download_count INT DEFAULT 0,approval_status VARCHAR(20) DEFAULT 'pending',FOREIGN KEY(department_id) REFERENCES departments(id),FOREIGN KEY(subject_id) REFERENCES subjects(id),FOREIGN KEY(uploader_id) REFERENCES users(id), INDEX search_title(title), INDEX search_topic(topic));
CREATE TABLE bookmarks (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,resource_id INT NOT NULL,category VARCHAR(50) DEFAULT 'Read Later',created_at DATETIME DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY unique_bookmark(user_id,resource_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(resource_id) REFERENCES resources(id) ON DELETE CASCADE);
CREATE TABLE ratings (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,resource_id INT NOT NULL,rating TINYINT NOT NULL,review TEXT,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY unique_rating(user_id,resource_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(resource_id) REFERENCES resources(id) ON DELETE CASCADE);
CREATE TABLE summaries (id INT AUTO_INCREMENT PRIMARY KEY,resource_id INT NOT NULL UNIQUE,summary TEXT NOT NULL,key_concepts TEXT,important_points TEXT,generated_at DATETIME DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(resource_id) REFERENCES resources(id) ON DELETE CASCADE);
CREATE TABLE user_activity (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,resource_id INT,activity_type VARCHAR(30) NOT NULL,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(resource_id) REFERENCES resources(id) ON DELETE SET NULL);
